#pragma once

#include <d3d9.h>

typedef enum 
{
	TEXTURE_INDEX_EXPLOSION,
	TEXTURE_INDEX_NUMBER,
	TEXTURE_INDEX_TITLE,
	TEXTURE_INDEX_RESULTCLEAR,
	TEXTURE_INDEX_RESULTOVER,
	TEXTURE_INDEX_SHUOMING,
	TEXTURE_INDEX_GAMECLEAR,
	TEXTURE_INDEX_GAMEOVER,
	TEXTURE_INDEX_JAINA,
	TEXTURE_INDEX_NZOTH,
	TEXTURE_INDEX_GAME,
	TEXTURE_INDEX_CAST,
	TEXTURE_INDEX_HOLE,
	TEXTURE_INDEX_SHADOW,
	TEXTURE_INDEX_CRACK,
	TEXTURE_INDEX_PLATFORM,
	TEXTURE_INDEX_HITPOINT,
	TEXTURE_INDEX_VALKYR,
	TEXTURE_INDEX_FROSTMAGE,
	TEXTURE_INDEX_PRESSENTER,
	TEXTURE_INDEX_ICON,

	TEXTURE_INDEX_FROSTBOLT,
	TEXTURE_INDEX_ICELANCE,
	TEXTURE_INDEX_ICEEFFECT3,
	TEXTURE_INDEX_SHIIMMER,
	TEXTURE_INDEX_FROSTNOVA,
	TEXTURE_INDEX_TIMEWARP,
	TEXTURE_INDEX_AECANEINTELLECT,
	TEXTURE_INDEX_FROZENORB,
	TEXTURE_INDEX_ICEBARRIER,
	TEXTURE_INDEX_ICEBLOCK,

    TEXTURE_INDEX_MAX
}TextureIndex;

int Texture_Load(void); //èâä˙âª
void Texture_Release(void); //èIóπèàóù
LPDIRECT3DTEXTURE9 Texture_GetTexture(TextureIndex index);
int Texture_GetWidth(TextureIndex index);
int Texture_GetHeight(TextureIndex index);